---
platform: "linux"
image_resource:
  type: "docker-image"
  source:
    repository: "dpb587/minio-bosh-release"
    tag: "ci-main"
inputs:
  - name: "working-tree"
  - name: "bosh-director"
  - name: "bosh-release"
  - name: "bosh-stemcell"
run:
  path: "working-tree/ci/tasks/integration-test/execute.sh"
