---
name: "subject"
releases:
  - name: "minio"
    version: "latest"
stemcells:
  - alias: "default"
    os: "ubuntu-trusty"
    version: "latest"
instance_groups:
  - name: "minio"
    instances: 1
    vm_type: "default"
    stemcell: "default"
    networks:
      - name: "default"
    azs:
      - "z1"
    jobs:
      - name: "minio"
        release: "minio"
        provides:
          storage:
            shared: true
        properties:
          scheme: "http"
          access_key: "aDifferentAccessKey"
          secret_key: "aDifferentSecretKey"
  - name: "make-bucket"
    lifecycle: "errand"
    instances: 1
    vm_type: "default"
    stemcell: "default"
    networks:
      - name: "default"
    azs:
      - "z1"
    jobs:
      - name: "mc-mb"
        release: "minio"
        properties:
          bucket: "minio-logs"
  - name: "mirror-push"
    lifecycle: "errand"
    instances: 1
    vm_type: "default"
    stemcell: "default"
    networks:
      - name: "default"
    azs:
      - "z1"
    jobs:
      - name: "mc-mirror"
        release: "minio"
        properties:
          path: "/var/vcap/bosh/bin/"
          remote_bucket: "minio-logs"
  - name: "mirror-pull"
    instances: 1
    vm_type: "default"
    stemcell: "default"
    networks:
      - name: "default"
    azs:
      - "z1"
    jobs:
      - name: "mc-mirror"
        release: "minio"
        properties:
          direction: "pull"
          path: "/var/vcap/data/mirror-pull/"
          remote_bucket: "minio-logs"
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
