---
name: "minio"
description: |
  A [BOSH](https://bosh.io) release to deploy [minio](https://www.minio.io/), a S3-compatible object storage server.
blobstore:
  provider: "s3"
  options:
    bucket_name: "dpb587-minio-bosh-release-us-east-1"
